pipeline {
    agent any // This is where we dont have any master or client setup, here pipeline will run on server itself
    tools {
        maven 'Maven3.9'
        jdk 'JDK17'
    }
    stages {
        stage('Fetch Code') {
            steps {
                git branch: 'atom', url: 'https://github.com/hkhcoder/vprofile-project.git'
            }
        }
        stage('Code Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
            post {
                success {
                    echo 'Archiving Artifact'
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Code Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Check Style Analysis') {
            steps {
                sh 'mvn checkstyle:checkstyle'
            }
        }
    }
}